apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "heimdall.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "heimdall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heimdall.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: config
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ template "heimdall.fullname" . }}-config-pvc
      {{- end }} 