{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pigallery2.fullname" . }}-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      {{- include "pigallery2.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "pigallery2.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        imagePullPolicy: {{ .Values.database.image.pullPolicy }}
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.existingSecret }}
              key: MYSQL_ROOT_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.existingSecret }}
              key: MYSQL_DATABASE
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.existingSecret }}
              key: MYSQL_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.existingSecret }}
              key: MYSQL_PASSWORD
        ports:
        - containerPort: {{ .Values.database.service.targetPort }}
          name: mysql
        {{- if .Values.database.resources }}
        resources:
          {{- toYaml .Values.database.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.database.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.database.persistence.mountPath }}
        {{- end }}
      {{- if .Values.database.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "pigallery2.fullname" . }}-db-pvc
      {{- end }}
{{- end }} 