{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    {{- include "pigallery2.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
    name: mysql
{{- end }} 