{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.secrets.mysql.database | b64enc }}
  MYSQL_USER: {{ .Values.secrets.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysql.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysql.rootPassword | b64enc }}
{{- end }} 