apiVersion: v1
kind: Service
metadata:
  name: {{ template "pigallery2.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pigallery2.selectorLabels" . | nindent 4 }} 